// main
export const SEND_REMOTE_REQUEST = 'SEND_REMOTE_REQUEST';
export const GET_REMOTE_ERROR = 'GET_REMOTE_ERROR';

// Study
export const GET_STUDIES_SUCCESS = 'GET_STUDIES_SUCCESS';
export const SHOW_NEXT_X_ITEMS_IN_FACET = 'SHOW_NEXT_X_ITEMS_IN_FACET';
export const SHOW_ALL_ITEMS_IN_FACET = 'SHOW_ALL_ITEMS_IN_FACET';
export const RESET_ITEMS_IN_FACET = 'RESET_ITEMS_IN_FACET';

export const TOGGLE_FACET_ITEM = 'TOGGLE_FACET_ITEM';
export const UPDATE_ACTIVE_STUDIES = 'UPDATE_ACTIVE_STUDIES';
export const RESET_ACTIVE_STUDIES = 'RESET_ACTIVE_STUDIES';
